### ISSUE TITLE
Anonymized Dumps including partitioned tables cannot be restored with parallel pg_restore (option -j | --jobs)

### ISSUE THREAD

**Issue by gp4git** [rjuju/pg_anonymize#3]
Hello,

first, thank you for releasing another PostgreSQL anonymization extension.

Test environment : PG v14.7 

As the title reads, when I pg_restore a pg_anonymized dump containing schemas with ***partitioned tables***
in parallel mode (-j option), I get the following errors :
pg_restore: error: COPY failed for table "<table_name>_p0": ERROR:  deadlock detected
DETAIL:  Process 27039 waits for RowExclusiveLock on relation 32978937 of database 32945391; blocked by process 27038.
Process 27038 waits for RowExclusiveLock on relation 32978892 of database 32945391; blocked by process 27039.

Notice : a normal dump (i.e. without pg_anonymize extension) of these same schemas is correctly restored in parallel mode.

Also, for the record, it is the exact same issue I reported in the PostgreSQL Anonymizer project.
See https://gitlab.com/dalibo/postgresql_anonymizer/-/issues/355

Regards

**Comment by gp4git** [comment]
Hi again,

Sorry to have been terse for the report.
Yes, I anonymize the partition key (partitioned by hash by the way) of the partitioned tables.
And I dump like this :

pg_dump -U rjuju --format=custom --schema '*_dba' --load-via-partition-root --no-security-labels -v -f /var/tmp/test.dmp test
Note the --load-via-partition-root option to correctly restore the partitions after anonymization.

And restore like this :
PGOPTIONS="-c maintenance_work_mem=256MB" pg_restore --dbname=test_anon --username=postgres --role=test_anon --no-owner --jobs=4 --exit-on-error --verbose /var/tmp/test.dmp 2>&1 | tee /var/tmp/log/restore_test_test_anon.log

I cannot give you more at the moment.

Regards

**Comment by gp4git** [comment]
Just to be clear :
When I pg_dump the same schemas under a normal role (i.e a role not loading your extension),
I can pg_restore it in parallel without any problem.
HTH
Regards

**Comment by rjuju** [comment]
Ok, I could reproduce it locally.  I didn't look at the pg_restore code yet so I'm not entirely sure of what the problem exactly is.  On the server side, what's happening is that you have

- session 1: BEGIN
- session 1: TRUNCATE TABLE ONLY hash_partition_1
- session 2: BEGIN
- session 2: TRUNCATE TABLE ONLY hash_partition_2
- session 1: COPY root_hash_table FROM stdin
- session 2: COPY root_hash_table FROM stdin

And as soon as session 1 is trying to insert into hash_partition_2 and session 2 is trying to insert into hash_partition_1 you get the deadlock.  That makes sense, however I'm not sure how it can work when the partitions data don't get interverted.  I'm also not sure how it wouldn't be a problem without pg_anonymize, for instance when trying the same scenario when restoring data on a different architecture (like little endian vs big endian) where the computed hash value would also differ from the original one.

Anyway, one easy way to workaround the problem is to restore the dump in multiple stage, something like:

```
PGOPTIONS="-c maintenance_work_mem=256MB" pg_restore --dbname=test_anon --username=postgres --role=test_anon --no-owner --jobs=4 --exit-on-error --verbose --section=pre-data /var/tmp/test.dmp 2>&1 | tee /var/tmp/log/restore_test_test_anon_pre_data.log

PGOPTIONS="-c maintenance_work_mem=256MB" pg_restore --dbname=test_anon --username=postgres --role=test_anon --no-owner --jobs=4 --exit-on-error --verbose --section=data /var/tmp/test.dmp 2>&1 | tee /var/tmp/log/restore_test_test_anon_data.log

PGOPTIONS="-c maintenance_work_mem=256MB" pg_restore --dbname=test_anon --username=postgres --role=test_anon --no-owner --jobs=4 --exit-on-error --verbose --section=post-data /var/tmp/test.dmp 2>&1 | tee /var/tmp/log/restore_test_test_anon_post_data.log
```

Can you confirm if it's enough for you to restore the dump?  If yes that's something that I will document.

On a related note, I see that the anonymization of dynamic SQL queries doesn't work well with partitioning (and maybe not with standard inheritance).  I will also work on that.

**Comment by rjuju** [comment]
Ok so after looking at pg_dump / pg_restore code, I confirm that my assumption was correct, and the same problem would occur if the different partition routing was caused by something else than pg_anonymize.

The reason it works in the normal case is that `--load-via-partition-root` only changes the COPY FROM table name, but you still get different TOC entries for each partition, and those are therefore dispatched between each parallel workers with their associated TRUNCATE ONLY statements accordingly.

**Comment by rjuju** [comment]
Note that [pg_dump documentation](https://www.postgresql.org/docs/current/app-pgdump.html) has some warning about it:

> --load-via-partition-root
> [...]
> It is best not to use parallelism when restoring from an archive made with this option, because pg_restore will not know exactly which partition(s) a given archive data item will load data into. This could result in inefficiency due to lock conflicts between parallel jobs, or perhaps even restore failures due to foreign key constraints being set up before all the relevant data is loaded.

So while it doesn't mention this scenario as a reason for restore failure, the hazard still exists and is (partially) documented.

**Comment by gp4git** [comment]
Hi,
thanks a lot for your explanation and the workaround that works great.
I also found these posts :
https://www.postgresql.org/message-id/flat/13624.1535486019%40sss.pgh.pa.us
I quote "I suspect that deadlock failures during restore are also possible"
I think the pg_dump documentation should be amended on that point.

Best Regards

**Comment by rjuju** [comment]
> thanks a lot for your explanation and the workaround that works great.

Ah great news!

> I also found these posts :
https://www.postgresql.org/message-id/flat/13624.1535486019%40sss.pgh.pa.us
I quote "I suspect that deadlock failures during restore are also possible"
I think the pg_dump documentation should be amended on that point.

Yeah, I restarted that discussion a few days ago with this case, and while it's not done yet probably we will patch pg_dump and/or pg_restore so that it doesn't fail anymore with this scenario.

**Comment by rjuju** [comment]
For the record there a fix for pg_dump on the way: https://www.postgresql.org/message-id/2441413.1678750752%40sss.pgh.pa.us for which I just finished the review.

As this is a bugfix it should be backported so hopefully all the next minor versions of pg_dump / pg_restore will be able to restore either existing and new dump using parallelism without any problem.

**Comment by rjuju** [comment]
> On a related note, I see that the anonymization of dynamic SQL queries doesn't work well with partitioning (and maybe not with standard inheritance). I will also work on that.

FTR I also fixed that a couple of days ago.  For now it's only for "direct" usage (when referencing the partitioned table for which a SECURITY LABEL has been defined), so the security labels are not inherited on the partitions yet, but that will be implemented soon.

**Comment by rjuju** [comment]
> For the record there a fix for pg_dump on the way: https://www.postgresql.org/message-id/2441413.1678750752%40sss.pgh.pa.us for which I just finished the review.
> 
> As this is a bugfix it should be backported so hopefully all the next minor versions of pg_dump / pg_restore will be able to restore either existing and new dump using parallelism without any problem.

And this has now been pushed and backported to pg11: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=bc8cd50fefd369b217f80078585c486505aafb62.

**Comment by gp4git** [comment]
Thanks a lot to have push for a quick fix and review it.
I will test the new minor release next May.

Best regards

**Comment by gp4git** [comment]
Hello,
I installed the last PG 14 version (14.8) and can confirmed that the bug is fixed
so closing this ticket.
Thanks a lot for your work on it.
Best regards

**Comment by rjuju** [comment]
Great news, thanks a lot for the confirmation!
